import type {
  NarrativeConfidence,
  NarrativeLiquidWater,
  NarrativePressureBasis,
  NarrativeVolcanism,
} from '@/features/content3d/narrative/types'

/**
 * Telemetry Deep History cho Trái Đất — tham chiếu mô hình hành tinh / địa chất (NASA PSD, phổ đo khí quyển sớm, MNBC, ma sát thủy triều ngày).
 * Mỗi beat có bộ số riêng; không dùng default chung cho mọi thời kỳ.
 */
export interface EarthStageTelemetry {
  confidence: NarrativeConfidence
  liquidWater: NarrativeLiquidWater
  volcanism: NarrativeVolcanism
  /** Độ dài ngày (giờ) — mô hình ma sát thủy triều Mặt Trăng (Williams 2000; zircon ~3,5 Ga). */
  dayLengthHours: number
  surfaceTempMinC: number
  surfaceTempMaxC: number
  surfacePressureRepresentativePa: number
  surfacePressureBasis: NarrativePressureBasis
  atmosphereThickness: number
  waterCoverage: number
  dustOpacity: number
  volcanicGlow: number
  environmentNoteVi: string
  compareNoteVi: string
}

/** Áp suất MNBC hiện đại (Pa) — chuẩn so sánh. */
export const EARTH_MNBC_PA = 101_325

export const EARTH_STAGE_TELEMETRY: Record<number, EarthStageTelemetry> = {
  0: {
    confidence: 'model',
    liquidWater: 'none',
    volcanism: 'dominant',
    dayLengthHours: 6,
    surfaceTempMinC: 800,
    surfaceTempMaxC: 1500,
    surfacePressureRepresentativePa: 0,
    surfacePressureBasis: 'hypothesis_range',
    atmosphereThickness: 0.05,
    waterCoverage: 0,
    dustOpacity: 0.85,
    volcanicGlow: 0.2,
    environmentNoteVi: 'Chưa có hành tinh Trái Đất riêng — đĩa tiền hành tinh (~4,6 Ga).',
    compareNoteVi: 'Giai đoạn tiền hành tinh; áp suất bề mặt chưa áp dụng.',
  },
  1: {
    confidence: 'model',
    liquidWater: 'none',
    volcanism: 'dominant',
    dayLengthHours: 6,
    surfaceTempMinC: 1200,
    surfaceTempMaxC: 2500,
    surfacePressureRepresentativePa: 50_000,
    surfacePressureBasis: 'hypothesis_range',
    atmosphereThickness: 0.35,
    waterCoverage: 0,
    dustOpacity: 0.9,
    volcanicGlow: 1,
    environmentNoteVi: 'Va chạm Theia (~4,5 Ga): bề mặt nóng chảy, khí quyển dày silicate.',
    compareNoteVi: 'Mặt Trăng hình thành từ mảnh vụn quỹ đạo — không còn bề mặt ổn định.',
  },
  2: {
    confidence: 'model',
    liquidWater: 'none',
    volcanism: 'dominant',
    dayLengthHours: 8,
    surfaceTempMinC: 700,
    surfaceTempMaxC: 1400,
    surfacePressureRepresentativePa: 80_000,
    surfacePressureBasis: 'hypothesis_range',
    atmosphereThickness: 0.4,
    waterCoverage: 0,
    dustOpacity: 0.75,
    volcanicGlow: 0.95,
    environmentNoteVi: 'Đại dương magma toàn cầu; CO₂ dày đặc, không O₂ tự do.',
    compareNoteVi: 'Áp suất và CO₂ cao hơn nhiều so với Trái Đất hiện đại (~420 ppm).',
  },
  3: {
    confidence: 'model',
    liquidWater: 'none',
    volcanism: 'high',
    dayLengthHours: 10,
    surfaceTempMinC: 85,
    surfaceTempMaxC: 220,
    surfacePressureRepresentativePa: 65_000,
    surfacePressureBasis: 'hypothesis_range',
    atmosphereThickness: 0.28,
    waterCoverage: 0,
    dustOpacity: 0.55,
    volcanicGlow: 0.7,
    environmentNoteVi: 'Vỏ đầu tiên (~4,0 Ga): bề mặt vẫn nóng, CO₂ ~4% khối lượng khí quyển (mô hình).',
    compareNoteVi: 'Ngày ~10 giờ (quay nhanh); chưa có đại dương lỏng bền vững.',
  },
  4: {
    confidence: 'model',
    liquidWater: 'rare',
    volcanism: 'high',
    dayLengthHours: 12,
    surfaceTempMinC: 45,
    surfaceTempMaxC: 120,
    surfacePressureRepresentativePa: 55_000,
    surfacePressureBasis: 'hypothesis_range',
    atmosphereThickness: 0.22,
    waterCoverage: 0.05,
    dustOpacity: 0.45,
    volcanicGlow: 0.35,
    environmentNoteVi: 'Bắn phá thiên thạch cuối (~3,9 Ga): va chạm dày, có thể mang nước băng.',
    compareNoteVi: 'Nhiệt bề mặt vẫn cao hơn hiện đại; O₂ vẫn ~0%.',
  },
  5: {
    confidence: 'model',
    liquidWater: 'regional',
    volcanism: 'moderate',
    dayLengthHours: 14,
    surfaceTempMinC: 15,
    surfaceTempMaxC: 75,
    surfacePressureRepresentativePa: 45_000,
    surfacePressureBasis: 'hypothesis_range',
    atmosphereThickness: 0.2,
    waterCoverage: 0.25,
    dustOpacity: 0.25,
    volcanicGlow: 0.2,
    environmentNoteVi: 'Đại dương lỏng đầu (~3,8 Ga, đại Cổ Sinh sớm); khí quyển giàu CO₂.',
    compareNoteVi: 'Bắt đầu có nước lỏng khu trú — tiền đề cho sự sống sơ khai.',
  },
  6: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'moderate',
    dayLengthHours: 15,
    surfaceTempMinC: 10,
    surfaceTempMaxC: 55,
    surfacePressureRepresentativePa: 38_000,
    surfacePressureBasis: 'model_range',
    atmosphereThickness: 0.18,
    waterCoverage: 0.45,
    dustOpacity: 0.15,
    volcanicGlow: 0.15,
    environmentNoteVi: 'Cyanobacteria (~3,5 Ga): quang hợp bắt đầu, O₂ vẫn rất thấp.',
    compareNoteVi: 'O₂ ~0,1% — chưa có sự kiện oxy hóa lớn.',
  },
  7: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'moderate',
    dayLengthHours: 18,
    surfaceTempMinC: 5,
    surfaceTempMaxC: 45,
    surfacePressureRepresentativePa: 30_000,
    surfacePressureBasis: 'model_range',
    atmosphereThickness: 0.16,
    waterCoverage: 0.55,
    dustOpacity: 0.1,
    volcanicGlow: 0.1,
    environmentNoteVi: 'Sự kiện oxy hóa lớn (~2,4 Ga): O₂ tích tụ, đại tuyệt chủng kỵ khí.',
    compareNoteVi: 'CO₂ giảm mạnh so với đại Cổ Sinh; khí quyển tiến gần hơn tới hiện đại.',
  },
  8: {
    confidence: 'consensus',
    liquidWater: 'regional',
    volcanism: 'low',
    dayLengthHours: 21,
    surfaceTempMinC: -35,
    surfaceTempMaxC: 5,
    surfacePressureRepresentativePa: 12_000,
    surfacePressureBasis: 'model_range',
    atmosphereThickness: 0.12,
    waterCoverage: 0.15,
    dustOpacity: 0.05,
    volcanicGlow: 0,
    environmentNoteVi: 'Trái Đất quả cầu tuyết (~700 Ma, kỳ Băng hà): băng toàn cầu, O₂ ~5%.',
    compareNoteVi: 'Nhiệt trung bình thấp; đại dương bị đóng băng phần lớn.',
  },
  9: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 21.5,
    surfaceTempMinC: 8,
    surfaceTempMaxC: 32,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.72,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Cambri (~540 Ma): O₂ ~12%, đa dạng sinh học bùng nổ.',
    compareNoteVi: 'Áp suất ~1 bar (MNBC); khí quyển có thể nhận biết với hiện đại.',
  },
  10: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 22,
    surfaceTempMinC: 10,
    surfaceTempMaxC: 30,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.75,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Ordovi (~450 Ma): O₂ ~14%, sinh vật biển đa dạng.',
    compareNoteVi: 'Gần điều kiện khí quyển hiện đại về áp suất.',
  },
  11: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 22,
    surfaceTempMinC: 12,
    surfaceTempMaxC: 34,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.7,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Devon (~380 Ma): O₂ ~21%, cá và thực vật trên cạn.',
    compareNoteVi: 'Rừng sơ khai; CO₂ ~2200 ppm (cao hơn hiện đại).',
  },
  12: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 22.5,
    surfaceTempMinC: 14,
    surfaceTempMaxC: 36,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.68,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Than Đá (~320 Ma): O₂ ~35%, rừng than đá.',
    compareNoteVi: 'O₂ cao kỷ lục đại Hiển Sinh; CO₂ thấp ~800 ppm.',
  },
  13: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'moderate',
    dayLengthHours: 23,
    surfaceTempMinC: 8,
    surfaceTempMaxC: 38,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.15,
    waterCoverage: 0.65,
    dustOpacity: 0.08,
    volcanicGlow: 0.15,
    environmentNoteVi: 'Đại tuyệt chủng Permi–Tam Điệp (~252 Ma): núi lửa Siberia, khí hậu nóng.',
    compareNoteVi: 'Đại tuyệt chủng lớn nhất lịch sử Trái Đất.',
  },
  14: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'moderate',
    dayLengthHours: 23,
    surfaceTempMinC: 10,
    surfaceTempMaxC: 35,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.7,
    dustOpacity: 0.03,
    volcanicGlow: 0.05,
    environmentNoteVi: 'Kỳ Tam Điệp (~230 Ma): khủng long sơ khai, siêu lục địa Pangea.',
    compareNoteVi: 'CO₂ ~1750 ppm — ấm hơn hiện đại.',
  },
  15: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 23,
    surfaceTempMinC: 12,
    surfaceTempMaxC: 33,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.72,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Jura (~150 Ma): O₂ ~26%, khí hậu ấm đồng nhất.',
    compareNoteVi: 'Thời hoàng kim khủng long; ngày ~23 giờ.',
  },
  16: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 23.5,
    surfaceTempMinC: 14,
    surfaceTempMaxC: 34,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.74,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Phấn trắng (~100 Ma): O₂ ~30%, khí hậu nhiệt đới rộng.',
    compareNoteVi: 'CO₂ ~1700 ppm trước sự kiện Chicxulub.',
  },
  17: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'high',
    dayLengthHours: 23.5,
    surfaceTempMinC: -5,
    surfaceTempMaxC: 25,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.18,
    waterCoverage: 0.6,
    dustOpacity: 0.35,
    volcanicGlow: 0.25,
    environmentNoteVi: 'Thiên thạch Chicxulub (~66 Ma): bụi/vụn che phủ, mùa đông va chạm.',
    compareNoteVi: 'Tuyệt chủng khủng long phi chim; khí quyển tạm thời giàu aerosol.',
  },
  18: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 23.7,
    surfaceTempMinC: 8,
    surfaceTempMaxC: 30,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.76,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Cổ Tân (~50 Ma): thú có vú đa dạng hóa sau K–Pg.',
    compareNoteVi: 'CO₂ ~1000 ppm — ấm hơn kỳ Holocene.',
  },
  19: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 23.9,
    surfaceTempMinC: 5,
    surfaceTempMaxC: 28,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.14,
    waterCoverage: 0.78,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Tân Tân (~10 Ma): đồng cỏ, tiền nhân ở châu Phi.',
    compareNoteVi: 'CO₂ ~350 ppm — gần mức tiền công nghiệp.',
  },
  20: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 24,
    surfaceTempMinC: -25,
    surfaceTempMaxC: 12,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.13,
    waterCoverage: 0.55,
    dustOpacity: 0.04,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Pleistocene (~20 ka): băng hà, Homo sapiens.',
    compareNoteVi: 'CO₂ ~200 ppm — thấp hơn tiền công nghiệp.',
  },
  21: {
    confidence: 'consensus',
    liquidWater: 'widespread',
    volcanism: 'low',
    dayLengthHours: 24,
    surfaceTempMinC: -10,
    surfaceTempMaxC: 38,
    surfacePressureRepresentativePa: EARTH_MNBC_PA,
    surfacePressureBasis: 'measured_global_average',
    atmosphereThickness: 0.15,
    waterCoverage: 0.71,
    dustOpacity: 0.02,
    volcanicGlow: 0,
    environmentNoteVi: 'Kỳ Holocene / hiện đại: O₂ ~21%, CO₂ ~420 ppm (2020s).',
    compareNoteVi: 'Áp suất bề mặt ~101 325 Pa (MNBC) — chuẩn so sánh trong app.',
  },
}

export function telemetryForEarthStage(stageId: number): EarthStageTelemetry {
  return EARTH_STAGE_TELEMETRY[stageId] ?? EARTH_STAGE_TELEMETRY[21]
}

export function dayLengthForEarthStage(stageId: number): number {
  return telemetryForEarthStage(stageId).dayLengthHours
}
