import { EarthStage } from '@/types'

export const earthHistoryData: EarthStage[] = [
  {
    id: 0,
    name: 'Đĩa tiền hành tinh',
    time: 4600,
    timeDisplay: '4.6 tỷ năm trước',
    eon: 'Hadean',
    era: null,
    period: null,
    o2: 0,
    co2: 0,
    dayLength: 6,
    earthColor: '#8B4513',
    hasDebris: true,
    description: 'Hệ Mặt Trời hình thành từ đám mây bụi và khí. Trái Đất bắt đầu tích tụ từ các mảnh vụn.',
    icon: '🌫️'
  },
  {
    id: 1,
    name: 'Va chạm Theia',
    time: 4500,
    timeDisplay: '4.5 tỷ năm trước',
    eon: 'Hadean',
    era: null,
    period: null,
    o2: 0,
    co2: 0,
    dayLength: 6,
    moonDistance: 5,
    earthColor: '#FF4500',
    hasMeteorites: true,
    description: 'Hành tinh Theia va chạm với Trái Đất, tạo ra Mặt Trăng từ mảnh vụn.',
    icon: '💥'
  },
  {
    id: 2,
    name: 'Đại dương magma',
    time: 4450,
    timeDisplay: '4.45 tỷ năm trước',
    eon: 'Hadean',
    era: null,
    period: null,
    o2: 0,
    co2: 50000,
    dayLength: 8,
    moonDistance: 8,
    earthColor: '#FF6347',
    description: 'Bề mặt Trái Đất là đại dương magma nóng chảy. Khí quyển đầy CO2.',
    icon: '🌋'
  },
  {
    id: 3,
    name: 'Vỏ đầu tiên',
    time: 4000,
    timeDisplay: '4 tỷ năm trước',
    eon: 'Hadean',
    era: null,
    period: null,
    o2: 0,
    co2: 40000,
    dayLength: 10,
    moonDistance: 10,
    earthColor: '#696969',
    hasMeteorites: true,
    description: 'Vỏ Trái Đất bắt đầu hình thành. Thời kỳ bắn phá thiên thạch nặng nề.',
    icon: '🪨'
  },
  {
    id: 4,
    name: 'Late Heavy Bombardment',
    time: 3900,
    timeDisplay: '3.9 tỷ năm trước',
    eon: 'Hadean',
    era: null,
    period: null,
    o2: 0,
    co2: 30000,
    dayLength: 12,
    moonDistance: 12,
    earthColor: '#4A4A4A',
    hasMeteorites: true,
    description: 'Thời kỳ bắn phá thiên thạch cuối. Nước được mang đến Trái Đất.',
    icon: '☄️'
  },
  {
    id: 5,
    name: 'Đại dương đầu tiên',
    time: 3800,
    timeDisplay: '3.8 tỷ năm trước',
    eon: 'Archean',
    era: null,
    period: null,
    o2: 0,
    co2: 20000,
    dayLength: 14,
    moonDistance: 15,
    earthColor: '#1E3A5F',
    atmosphereColor: '#8B4513',
    description: 'Đại dương lỏng đầu tiên xuất hiện. Sự sống có thể đã bắt đầu.',
    icon: '🌊'
  },
  {
    id: 6,
    name: 'Vi khuẩn lam',
    time: 3500,
    timeDisplay: '3.5 tỷ năm trước',
    eon: 'Archean',
    era: null,
    period: null,
    o2: 0.1,
    co2: 15000,
    dayLength: 15,
    moonDistance: 18,
    earthColor: '#2E4A62',
    atmosphereColor: '#CD853F',
    description: 'Vi khuẩn lam (Cyanobacteria) xuất hiện, bắt đầu quang hợp.',
    icon: '🦠'
  },
  {
    id: 7,
    name: 'Great Oxidation Event',
    time: 2400,
    timeDisplay: '2.4 tỷ năm trước',
    eon: 'Proterozoic',
    era: null,
    period: null,
    o2: 2,
    co2: 5000,
    dayLength: 18,
    moonDistance: 25,
    earthColor: '#4169E1',
    atmosphereColor: '#B8860B',
    description: 'Oxy tích tụ trong khí quyển. Đại tuyệt chủng đầu tiên của sinh vật kỵ khí.',
    icon: '💨'
  },
  {
    id: 8,
    name: 'Trái Đất Tuyết (Snowball Earth)',
    time: 700,
    timeDisplay: '700 triệu năm trước',
    eon: 'Proterozoic',
    era: 'Neoproterozoic',
    period: 'Cryogenian',
    o2: 5,
    co2: 1000,
    dayLength: 21,
    moonDistance: 35,
    earthColor: '#E0FFFF',
    atmosphereColor: '#87CEEB',
    description: 'Trái Đất đóng băng hoàn toàn. Nhiệt độ cực thấp toàn cầu.',
    icon: '❄️'
  },
  {
    id: 9,
    name: 'Bùng nổ Cambrian',
    time: 540,
    timeDisplay: '540 triệu năm trước',
    maxMa: 538.8,
    minMa: 485.4,
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Cambrian',
    o2: 12,
    co2: 4500,
    dayLength: 21.5,
    moonDistance: 38,
    earthColor: '#20B2AA',
    atmosphereColor: '#4682B4',
    description: 'Sự bùng nổ đa dạng sinh học. Hầu hết các ngành động vật xuất hiện.',
    icon: '🦑'
  },
  {
    id: 10,
    name: 'Kỷ Ordovician',
    time: 450,
    timeDisplay: '450 triệu năm trước',
    maxMa: 485.4,
    minMa: 443.8,
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Ordovician',
    o2: 14,
    co2: 4000,
    dayLength: 22,
    moonDistance: 38,
    earthColor: '#3CB371',
    atmosphereColor: '#5F9EA0',
    description: 'Đa dạng sinh vật biển. Cá không hàm xuất hiện.',
    icon: '🐚'
  },
  {
    id: 11,
    name: 'Kỷ Devonian - Cá chinh phục',
    time: 380,
    timeDisplay: '380 triệu năm trước',
    maxMa: 419.2,
    minMa: 358.9,
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Devonian',
    o2: 21,
    co2: 2200,
    dayLength: 22,
    moonDistance: 38,
    earthColor: '#228B22',
    atmosphereColor: '#87CEEB',
    description: 'Thời đại của cá. Động vật đầu tiên lên cạn. Rừng đầu tiên xuất hiện.',
    icon: '🐟'
  },
  {
    id: 12,
    name: 'Kỷ Carboniferous - Rừng than đá',
    time: 320,
    timeDisplay: '320 triệu năm trước',
    maxMa: 358.9,
    minMa: 298.9,
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Carboniferous',
    o2: 35,
    co2: 800,
    dayLength: 22.5,
    moonDistance: 38,
    earthColor: '#006400',
    atmosphereColor: '#90EE90',
    description: 'Rừng khổng lồ phủ kín đất liền. Côn trùng khổng lồ. Than đá hình thành.',
    icon: '🌲'
  },
  {
    id: 13,
    name: 'Đại tuyệt chủng Permian',
    time: 252,
    timeDisplay: '252 triệu năm trước',
    maxMa: 298.9,
    minMa: 251.9,
    eon: 'Phanerozoic',
    era: 'Paleozoic',
    period: 'Permian',
    o2: 23,
    co2: 900,
    dayLength: 23,
    moonDistance: 38,
    earthColor: '#8B0000',
    atmosphereColor: '#FF6347',
    isExtinction: true,
    description: 'Đại tuyệt chủng lớn nhất. 96% sinh vật biển, 70% trên cạn bị tiêu diệt.',
    icon: '💀'
  },
  {
    id: 14,
    name: 'Kỷ Triassic - Khủng long đầu tiên',
    time: 230,
    timeDisplay: '230 triệu năm trước',
    maxMa: 251.9,
    minMa: 201.3,
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Triassic',
    o2: 16,
    co2: 1750,
    dayLength: 23,
    moonDistance: 38,
    earthColor: '#D2691E',
    atmosphereColor: '#F4A460',
    description: 'Khủng long, thú có vú và pterosaur đầu tiên xuất hiện.',
    icon: '🦎'
  },
  {
    id: 15,
    name: 'Kỷ Jurassic - Thời đại Khủng long',
    time: 150,
    timeDisplay: '150 triệu năm trước',
    maxMa: 201.3,
    minMa: 145,
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Jurassic',
    o2: 26,
    co2: 1950,
    dayLength: 23,
    moonDistance: 38,
    earthColor: '#32CD32',
    atmosphereColor: '#98FB98',
    description: 'Thời hoàng kim của khủng long. Chim đầu tiên (Archaeopteryx).',
    icon: '🦕'
  },
  {
    id: 16,
    name: 'Kỷ Cretaceous',
    time: 100,
    timeDisplay: '100 triệu năm trước',
    maxMa: 145,
    minMa: 66,
    eon: 'Phanerozoic',
    era: 'Mesozoic',
    period: 'Cretaceous',
    o2: 30,
    co2: 1700,
    dayLength: 23.5,
    moonDistance: 38,
    earthColor: '#7CFC00',
    atmosphereColor: '#ADFF2F',
    description: 'Khủng long đạt đỉnh cao đa dạng. Thực vật có hoa xuất hiện.',
    icon: '🦖'
  },
  {
    id: 17,
    name: 'Thiên thạch Chicxulub',
    time: 66,
    timeDisplay: '66 triệu năm trước',
    maxMa: 70,
    minMa: 62,
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    o2: 23,
    co2: 500,
    dayLength: 23.5,
    moonDistance: 38,
    earthColor: '#696969',
    atmosphereColor: '#A9A9A9',
    hasMeteorites: true,
    isExtinction: true,
    description: 'Thiên thạch đường kính 10km đâm vào Mexico. Tuyệt chủng khủng long.',
    icon: '☄️'
  },
  {
    id: 18,
    name: 'Kỷ Paleogene - Thú có vú lên ngôi',
    time: 50,
    timeDisplay: '50 triệu năm trước',
    maxMa: 66,
    minMa: 23.03,
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Paleogene',
    o2: 23,
    co2: 1000,
    dayLength: 23.7,
    moonDistance: 38,
    earthColor: '#228B22',
    atmosphereColor: '#87CEEB',
    description: 'Thú có vú đa dạng hóa nhanh chóng. Cá voi, dơi, linh trưởng xuất hiện.',
    icon: '🐘'
  },
  {
    id: 19,
    name: 'Kỷ Neogene',
    time: 10,
    timeDisplay: '10 triệu năm trước',
    maxMa: 23.03,
    minMa: 2.58,
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Neogene',
    o2: 21,
    co2: 350,
    dayLength: 23.9,
    moonDistance: 38,
    earthColor: '#2E8B57',
    atmosphereColor: '#87CEEB',
    description: 'Đồng cỏ mở rộng. Tổ tiên loài người xuất hiện ở châu Phi.',
    icon: '🦁'
  },
  {
    id: 20,
    name: 'Kỷ Băng hà Pleistocene',
    time: 0.02,
    timeDisplay: '20,000 năm trước',
    maxMa: 2.58,
    minMa: 0,
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    o2: 21,
    co2: 200,
    dayLength: 24,
    moonDistance: 38,
    earthColor: '#B0E0E6',
    atmosphereColor: '#E0FFFF',
    description: 'Kỷ băng hà cuối cùng. Homo sapiens di cư khắp thế giới.',
    icon: '🦣'
  },
  {
    id: 21,
    name: 'Trái Đất hiện đại',
    time: 0,
    timeDisplay: 'Hiện tại',
    maxMa: 0.012,
    minMa: 0,
    eon: 'Phanerozoic',
    era: 'Cenozoic',
    period: 'Quaternary',
    o2: 21,
    co2: 420,
    dayLength: 24,
    moonDistance: 38,
    earthColor: '#1E90FF',
    atmosphereColor: '#87CEEB',
    textureUrl: '/textures/8k_earth_daymap.jpg',
    description: 'Trái Đất ngày nay với 8 tỷ con người. Biến đổi khí hậu đang diễn ra.',
    icon: '🌍'
  }
]

export const getStageByTime = (time: number): EarthStage | undefined => {
  const exact = earthHistoryData.find(s => s.time === time)
  if (exact) return exact
  const tolerance = time >= 1 ? time * 0.1 : 0.5
  return earthHistoryData.find(stage => Math.abs(stage.time - time) <= tolerance)
}

export const getStageById = (id: number): EarthStage | undefined => {
  return earthHistoryData.find(stage => stage.id === id)
}
