/**
 * Tên biến môi trường dùng chung (API, client, Render Blueprint).
 * Giá trị URL/cổng chỉ đặt trong .env — không hardcode trong mã nguồn.
 */
const ENV = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',

  MONGODB_URI: 'MONGODB_URI',
  JWT_SECRET: 'JWT_SECRET',
  INTERNAL_API_SECRET: 'INTERNAL_API_SECRET',

  /** URL gốc Next.js (CORS, redirect thanh toán, email). */
  CLIENT_URL: 'CLIENT_URL',
  /** URL công khai API (IPN VNPay, OAuth callback docs). */
  API_PUBLIC_URL: 'API_PUBLIC_URL',

  /** Gốc unified API cho browser (không có /api ở cuối). */
  NEXT_PUBLIC_API_BASE_URL: 'NEXT_PUBLIC_API_BASE_URL',
  /** Dev: Next proxy → unified API. */
  API_PROXY_TARGET: 'API_PROXY_TARGET',
  /** Next rewrite /media → host phục vụ file. */
  MEDIA_SERVICE_URL: 'MEDIA_SERVICE_URL',

  NEXT_PUBLIC_MEDIA_CDN: 'NEXT_PUBLIC_MEDIA_CDN',
  NEXT_PUBLIC_EARTH_HISTORY_API_URL: 'NEXT_PUBLIC_EARTH_HISTORY_API_URL',

  EMBEDDING_URL: 'EMBEDDING_URL',
  AI_SERVICE_URL: 'AI_SERVICE_URL',

  VNPAY_TMN_CODE: 'VNPAY_TMN_CODE',
  VNPAY_HASH_SECRET: 'VNPAY_HASH_SECRET',
  VNPAY_HOST: 'VNPAY_HOST',
  VNPAY_TEST_MODE: 'VNPAY_TEST_MODE',

  S3_MEDIA_BUCKET: 'S3_MEDIA_BUCKET',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION: 'AWS_REGION',
  MEDIA_CDN_URL: 'MEDIA_CDN_URL',

  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  FACEBOOK_APP_ID: 'FACEBOOK_APP_ID',
  FACEBOOK_APP_SECRET: 'FACEBOOK_APP_SECRET',
  FIREBASE_SERVICE_ACCOUNT_JSON: 'FIREBASE_SERVICE_ACCOUNT_JSON',

  SMTP_HOST: 'SMTP_HOST',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  MAIL_FROM: 'MAIL_FROM',
};

module.exports = ENV;
